### ISSUE TITLE
next can be called more then once

### ISSUE THREAD

**Issue by calvinmetcalf** [bucaran/kthulhu#3]
probably want to either do something to prevent it from being called multiple times like

```js
var done, promise = new Promise(function (resolve, reject){
  done = function (err, resp) {
    if (err) {
        return reject(err)
    }
    resolve(resp);
  })
});
```

or just don't pass the next call to the transform

**Comment by bucaran** [comment]
:+1:  Alright, let me think about this one. Some people may still wish to opt in for callbacks, so passing `next` and adding a little more code to skip using promises in such a special case might be the way to go in the next release.

**Comment by bucaran** [comment]
Related #4

**Comment by bucaran** [comment]
We need to pass `next()` to the transform to allow callback style as requested in #4.
