### ISSUE TITLE
Support callbacks for async stuff

### ISSUE THREAD

**Issue by alessioalex** [bucaran/kthulhu#4]
Perhaps allow a second argument as a callback to determine that it's async:

```js
// Just passing through!
process.stdin.pipe($(function (chunk, next) { 
  setTimeout(function() {
    next(null, chunk)
  })
})).pipe(process.stdout)
```

**Comment by bucaran** [comment]
@alessioalex Thanks! :+1: 

Definitely will add support for this as soon as a I get a chance.

**Comment by calvinmetcalf** [comment]
If you where to look at function.length (which corisponds to number of named arguments) you could use this to switch between promises and callbacks

Another option would be only treat the return from the function as something to resolve into a promise if it's truthy (or just not undefined)

**Comment by bucaran** [comment]
Done.

```js
process.stdin.pipe($(function (chunk, _, next) {
  setTimeout(function() {
    next(null, chunk.toString().toUpperCase())
  }, 5000)
})).pipe(process.stdout)
```
